export const FIRST_STEP = "Read the request";

export const PICKED_LINES = [
    "Working with your pick",
    "Building on your choice",
    "Taking your pick forward",
    "Shaping your pick",
    "Good choice, working it out",
];

export const STEP_LINES = {
    "Read the request": [
        "Reading your request",
        "Getting to know what you want",
        "Taking it all in",
        "Seeing the idea behind it",
        "Looking at the board for context",
        "Lining it up with what's already there",
        "Finding the heart of it",
        "Picking out what matters most",
        "Getting a feel for the goal",
        "Sketching a first picture",
        "Following your thinking",
        "Seeing where this could go",
        "Gathering the first clues",
        "Connecting it to the project",
        "Building a first idea of it",
        "Noting the key words",
        "Seeing what it would make possible",
        "Shaping a first take",
        "Getting ready to ask the right thing",
        "Off to a good start",
    ],
    "Find the feature (score 1)": [
        "A first idea is taking shape",
        "A few good directions come to mind",
        "Seeing which feature fits best",
        "Lining up the likeliest options",
        "Matching them against the board",
        "Keeping the strongest ideas",
        "Picking three good candidates",
        "Putting the best guess first",
        "Making the options easy to compare",
        "Saying what each would give you",
        "Getting the choices ready for you",
        "One of these will be it",
        "Checking nothing obvious is missing",
        "Narrowing it down nicely",
        "Almost ready to ask which one",
        "Making it a quick pick",
        "The options look promising",
        "Getting closer to your idea",
        "Nearly there with the options",
        "Ready to let you choose",
    ],
    "Pin it down (score 2)": [
        "I know roughly what you want",
        "The outline is clear",
        "Filling in the details",
        "Sharpening the picture",
        "Seeing how it should behave",
        "Working out where it shows up",
        "Thinking about who uses it",
        "Weighing a few good ways to build it",
        "Choosing the one question that matters",
        "Deciding what I can settle myself",
        "Keeping the question simple",
        "Making every answer count",
        "Getting a firm grip on it",
        "Well on the way",
        "Half the picture is in place",
        "Building on what you told me",
        "Getting more precise",
        "The idea is coming together",
        "A good shape is forming",
        "Almost ready to ask",
    ],
    "Make it concrete (score 3)": [
        "I mostly understand what you want",
        "The picture is getting clear",
        "Making it concrete",
        "Turning it into something buildable",
        "Picturing the finished thing",
        "Working out the first piece",
        "Checking the details that matter",
        "Seeing what it touches",
        "Finding the one detail still missing",
        "Checking it fits with the rest",
        "Picturing how you would use it",
        "Settling what I can on my own",
        "Picking the last question worth asking",
        "Sorting must-haves from nice-to-haves",
        "Seeing where it starts and ends",
        "Looking for a hidden snag",
        "Confident about most of it",
        "Getting the shape right",
        "Only a detail or two left",
        "Nearly clear enough to draft",
    ],
    "Settle the scope (score 4)": [
        "I know what you want",
        "Clear on the feature now",
        "Settling how big it should be",
        "Weighing a small start against the whole",
        "Seeing what can wait for later",
        "Choosing what belongs in this round",
        "Drawing the line around it",
        "Picking the size that ships soon",
        "Thinking about what comes first",
        "Seeing how many cards it needs",
        "Keeping the first round lean",
        "Checking nothing essential is cut",
        "Framing the scope question",
        "Making the choice quick for you",
        "One last check before drafting",
        "Confident in the plan",
        "Just the size left to settle",
        "Ready once the scope is set",
        "Closing the last gap",
        "Almost there",
    ],
    "Guess the count": [
        "Sizing up the cards",
    ],
    "Draft the cards": [
        "Writing the cards",
    ],
    "Offer groups": [
        "Grouping the cards",
    ],
    "Say one line": [
        "Finishing up",
    ],
    "Read the change": [
        "Reading your change",
    ],
    "Change the drafts": [
        "Updating the cards",
    ],
};
