export const FIRST_STEP = "Read the request";

export const PICKED_LINES = [
    "Working with your pick",
    "Building on your choice",
    "Taking your pick forward",
    "Shaping your pick",
    "Good choice, working it out",
];

export const STEP_LINES = {
    "Read the request": [
        "Reading your request",
        "Getting to know what you want",
        "Taking it all in",
        "Seeing the idea behind it",
        "Looking at the board for context",
        "Lining it up with what's already there",
        "Finding the heart of it",
        "Picking out what matters most",
        "Getting a feel for the goal",
        "Sketching a first picture",
        "Following your thinking",
        "Seeing where this could go",
        "Gathering the first clues",
        "Connecting it to the project",
        "Building a first idea of it",
        "Noting the key words",
        "Seeing what it would make possible",
        "Shaping a first take",
        "Getting ready to ask the right thing",
        "Off to a good start",
    ],
    "Name the goal (score 1)": [
        "Getting a feel for the goal",
        "Your goal is taking shape",
        "Looking for what the finished thing does",
        "Naming what you are after",
        "Finding the heart of it",
        "Seeing what success looks like for you",
        "A goal is coming into view",
        "Putting your goal into words",
        "Checking the goal against the board",
        "Good start, narrowing it down",
        "Sketching the end result",
        "Working out what matters most",
    ],
    "Set the scope (score 2)": [
        "Drawing the edges of this round",
        "Sorting what belongs now from what can wait",
        "Keeping the scope tight",
        "Weighing what goes in first",
        "Trimming to what matters now",
        "Marking what is in and what is out",
        "The shape is getting clearer",
        "Fencing in this round",
        "Deciding what can wait for later",
        "Making the round small enough to finish",
        "Good, the scope is firming up",
        "Lining up the pieces that belong",
    ],
    "Say what done means (score 3)": [
        "Turning the goal into checks",
        "Naming how you will know it works",
        "Writing down what done looks like",
        "Making each check testable",
        "Getting concrete about done",
        "Lining up checks you can see pass",
        "Nearly there: what counts as finished",
        "Pinning the finish line",
        "Checking each part of the goal has a test",
        "Spelling out done in plain words",
        "Good, done is getting clear",
        "Making sure nothing is left vague",
    ],
    "Choose the first slice (score 4)": [
        "Picking what should work first",
        "Finding the smallest useful step",
        "Ordering the work",
        "Almost ready to draft",
        "Choosing a first slice you can try",
        "Lining up what comes first",
        "Finding a first step that stands alone",
        "Good, the plan is nearly complete",
        "Deciding where to start",
        "Putting the first slice at the front",
    ],
    "Guess the count": ["Sizing up the cards"],
    "Map the work": ["Mapping the work"],
    "Draft the cards": ["Writing the cards"],
    "Check against the goal": ["Checking every part of the goal is covered"],
    "Offer groups": ["Grouping the cards"],
    "Say one line": ["Finishing up"],
    "Read the change": ["Reading your change"],
    "Change the drafts": ["Updating the cards"],
    "Recheck the drafts": ["Rechecking the drafts"],
};

export const STEP_WORDS = {
    "Read the request": "Reading the request",
    "Name the goal (score 1)": "Naming the goal",
    "Set the scope (score 2)": "Setting the scope",
    "Say what done means (score 3)": "Saying what done means",
    "Choose the first slice (score 4)": "Choosing the first slice",
    "Guess the count": "Counting the tickets",
    "Map the work": "Mapping the work",
    "Draft the cards": "Drafting tickets",
    "Check against the goal": "Checking against the goal",
    "Offer groups": "Grouping the drafts",
    "Say one line": "Wrapping up",
    "Read the change": "Reading your change",
    "Change the drafts": "Redrafting",
    "Recheck the drafts": "Rechecking the drafts",
};
