export const FIRST_STEP = "Read the request";

export const STEP_LINES = {
    "Read the request": [
        "Guessing what you want",
        "Checking whether I understand you",
        "Trying to follow what you mean",
        "Not sure yet what you are after",
        "Wondering what you have in mind",
        "Looking for a first clue",
        "Reading your words for a hint",
        "Asking myself what you need",
        "Trying a first guess",
        "Testing that guess against the board",
        "Seeing if the board gives it away",
        "Looking at what is already there for clues",
        "Checking I have not misread you",
        "Still guessing",
        "Trying another reading",
        "Weighing a few possible meanings",
        "Not assuming anything yet",
        "Checking how much I really know",
        "Working out where to begin",
        "Deciding how well I follow you",
    ],
    "Find the feature (score 1)": [
        "Starting to see what you might mean",
        "Getting a first idea of it",
        "A few meanings come to mind",
        "Guessing which feature you mean",
        "Not sure which one it is yet",
        "Narrowing down the possibilities",
        "Checking my guesses against the board",
        "Dropping the guesses that do not fit",
        "Keeping the likeliest ones",
        "Picking three I think you mean",
        "Putting my best guess first",
        "Making the guesses easy to tell apart",
        "Saying what each would give you",
        "Hoping one of these is it",
        "Asking you to point the way",
        "Letting you choose the feature",
        "Checking I have not missed an obvious one",
        "Getting my first guesses ready",
        "Almost ready to ask which one",
        "One of these should be close",
    ],
    "Pin it down (score 2)": [
        "I know roughly what you want",
        "The outline is getting clearer",
        "Pinning down the vague part",
        "Finding what I still do not know",
        "Seeing the biggest open question",
        "Checking my picture of it with you",
        "Filling in what I am unsure of",
        "Thinking about how it should behave",
        "Wondering where it should show up",
        "Working out who it is for",
        "Weighing a few ways it could work",
        "Choosing the one question that matters",
        "Leaving out what I can decide myself",
        "Framing the question simply",
        "Making every answer useful",
        "Getting a firmer grip on it",
        "Closer to what you want",
        "Half the picture is there",
        "Checking the half I have",
        "Almost ready to ask",
    ],
    "Make it concrete (score 3)": [
        "I mostly understand what you want",
        "The picture is getting clear",
        "Making it concrete",
        "Turning it into something buildable",
        "Picturing the finished thing",
        "Working out the first piece",
        "Checking the details that matter",
        "Seeing what it touches",
        "Finding the one detail still missing",
        "Checking it fits with the rest",
        "Picturing how you would use it",
        "Settling what I can on my own",
        "Picking the last question worth asking",
        "Sorting must-haves from nice-to-haves",
        "Seeing where it starts and ends",
        "Looking for a hidden snag",
        "Confident about most of it",
        "Getting the shape right",
        "Only a detail or two left",
        "Nearly clear enough to draft",
    ],
    "Settle the scope (score 4)": [
        "I know what you want",
        "Clear on the feature now",
        "Settling how big it should be",
        "Weighing a small start against the whole",
        "Seeing what can wait for later",
        "Choosing what belongs in this round",
        "Drawing the line around it",
        "Picking the size that ships soon",
        "Thinking about what comes first",
        "Seeing how many cards it needs",
        "Keeping the first round lean",
        "Checking nothing essential is cut",
        "Framing the scope question",
        "Making the choice quick for you",
        "One last check before drafting",
        "Confident in the plan",
        "Just the size left to settle",
        "Ready once the scope is set",
        "Closing the last gap",
        "Almost there",
    ],
    "Guess the count": [
        "Counting the cards this needs",
        "Guessing how many cards",
        "Splitting it into pieces",
        "Seeing what can ship on its own",
        "Looking at what is already there",
        "Finding the natural seams",
        "Deciding what goes together",
        "Keeping each card small",
        "Checking for overlap with other cards",
        "Weighing one card against two",
        "Sizing each piece",
        "Laying out the pieces",
        "Setting a low first guess",
        "Leaving room for more",
        "Ordering the pieces",
        "Checking the count again",
        "Making sure nothing is missed",
        "Seeing which pieces depend on others",
        "Settling the first guess",
        "Getting ready to draft",
    ],
    "Draft the cards": [
        "Drafting the cards",
        "Writing the first card",
        "Writing the next card",
        "Naming each card plainly",
        "Saying what each card delivers",
        "Keeping each card to one thing",
        "Writing what done looks like",
        "Checking each card stands alone",
        "Noting which card waits on which",
        "Putting the cards in order",
        "Making the titles short",
        "Filling in the details",
        "Checking the cards cover it all",
        "Trimming what is not needed",
        "Adding a card that was missing",
        "Reading the cards back",
        "Checking the cards against your request",
        "Tidying the wording",
        "Finishing the last card",
        "Nearly done drafting",
    ],
    "Say one line": [
        "Wrapping up",
        "Summing it up in one line",
        "Checking the cards once more",
        "Picking the words for you",
        "Keeping it to one line",
        "Saying what the cards cover",
        "Saying what you can do next",
        "Reading the line back",
        "Making it short",
        "Making it plain",
        "Checking nothing is left out",
        "Pointing at what matters",
        "Getting the tone right",
        "Leaving the choice to you",
        "Putting it in the panel",
        "Nearly finished",
        "One last look",
        "Finishing up",
        "Handing it over",
        "Done in a moment",
    ],
    "Read the change": [
        "Reading your change",
        "Seeing which cards you mean",
        "Finding the cards it touches",
        "Leaving the other cards alone",
        "Reading the cards you named",
        "Seeing what you want different",
        "Weighing the change",
        "Checking what else it affects",
        "Looking at the waits between cards",
        "Seeing if a card should split",
        "Seeing if cards should merge",
        "Checking the order still holds",
        "Noting what stays the same",
        "Reading it once more",
        "Matching the change to the cards",
        "Getting the change straight",
        "Checking nothing else needs to move",
        "Deciding how to change them",
        "Planning the edits",
        "Ready to change the drafts",
    ],
    "Change the drafts": [
        "Changing the drafts",
        "Rewriting the card you named",
        "Adjusting the wording",
        "Updating what the card delivers",
        "Splitting the card",
        "Merging the cards",
        "Adding the card you asked for",
        "Taking out the card you dropped",
        "Fixing the order",
        "Updating the waits between cards",
        "Keeping the rest as it was",
        "Checking the changed cards",
        "Reading the new version back",
        "Making the titles match",
        "Trimming the details",
        "Checking the change is complete",
        "Checking the cards still cover it",
        "Tidying up",
        "Finishing the last change",
        "Nearly done changing",
    ],
};
