
const KINDS = {
    waiting: {many: "Needs you"},
    todo: {
        one: "To-do",
        word: "to-do",
        many: "To-dos",
        icon: "todos",
        intro: "What the agent is asked to do in this environment.",
        make: "New to-do",
    },
    plan: {
        one: "Plan",
        word: "plan",
        many: "Plans",
        waiting: "Plan to approve",
        icon: "plan",
        intro: "Plans the agent wrote. Approve one and it starts.",
        description: "Plans the agent wrote; approve one to start it",
        make: "New plan",
    },
    suggestion: {
        one: "Suggestion",
        word: "suggestion",
        many: "Suggestions",
        icon: "bulb",
        intro: "Things the agent proposes. Pick an answer or write your own.",
        description: "Things the agent proposes for you to pick",
    },
    question: {
        one: "Question",
        word: "question",
        many: "Questions",
        icon: "questions",
        intro: "Questions the agent asked you.",
        description: "Questions the agent asked you",
    },
    collection: {
        one: "Collection",
        word: "collection",
        many: "Collections",
        icon: "folder",
        intro: "Items and files you grouped together.",
        description: "Items and files you grouped",
        make: "New collection",
    },
    work: {
        one: "Work",
        word: "work",
        many: "Work",
        icon: "work",
        intro: "Work the agents are doing right now.",
        description: "What the agents are doing now",
    },
    agent: {
        one: "Agent",
        word: "agent",
        many: "Agents",
        icon: "agents",
        get intro() {
            return `The main agent and its subagents.`;
        },
        get description() {
            return `The main agent and its subagents, and who started whom`;
        },
    },
    doc: {
        one: "Document",
        word: "document",
        many: "Documents",
        waiting: "New document",
        icon: "docs",
        intro: "Documents of the whole project: designs, briefs, notes.",
        description: "Designs, briefs and notes, sorted into groups",
        make: "New document",
    },
    ticket: {
        one: "Ticket",
        word: "ticket",
        many: "Tickets",
        icon: "ticket",
        intro: "Tickets on the board. Each one is worked by its own agent.",
        description: "Tickets on the board. Each one is worked by its own agent.",
        make: "New ticket",
    },
    trigger: {
        one: "Trigger",
        word: "trigger",
        many: "Triggers",
        icon: "bolt",
        intro: "Rules that start an action when you say a phrase or a time comes.",
        description: "Rules that start an action when you say a phrase or a time comes",
        make: "New trigger",
    },
    sequence: {
        one: "Sequence",
        word: "sequence",
        many: "Sequences",
        icon: "loop",
        intro: "Steps the agent goes through in order.",
        description: "Steps the agent runs in order",
        make: "New sequence",
    },
    check: {
        one: "Check",
        word: "check",
        many: "Checks",
        icon: "checkbox",
        intro: "Checks that run over the code and report what they find.",
        description: "What the code checks found",
    },
    message: {
        one: "Message",
        word: "message",
        many: "Messages",
        icon: "inbox",
        get intro() {
            return `Messages between agents and from subagents.`;
        },
        description: "Messages between agents",
    },
    report: {
        one: "Report",
        word: "report",
        many: "Reports",
        waiting: "New report",
        icon: "reports",
        intro: "What the agent reports when a job ends.",
        description: "What the agent reports when a job ends",
    },
    fact: {
        one: "Fact",
        word: "fact",
        many: "Facts",
        icon: "pins",
        intro: "Things the agent learned about this project and keeps in mind.",
        description: "What the agent learned about the project",
        make: "New fact",
    },
    reminder: {
        one: "Reminder",
        word: "reminder",
        many: "Reminders",
        icon: "reminders",
        intro: "Things the agent is reminded of at set moments.",
        description: "What the agent is reminded of, and when",
        make: "New reminder",
    },
    rule: {
        one: "Rule",
        word: "rule",
        many: "Rules",
        icon: "rules",
        intro: "Rules the agent follows in every session.",
        description: "Rules the agent follows every session",
        make: "New rule",
    },
    skill: {
        one: "Skill",
        word: "skill",
        many: "Skills",
        icon: "book",
        intro: "The instructions the agent loads for each kind of work.",
        description: "Instructions for each kind of work",
    },
    tool: {
        one: "Tool",
        word: "tool",
        many: "Tools",
        icon: "tools",
        intro: "Commands the agent may run for this project.",
        description: "Commands the agent may run",
        make: "New tool",
        runs: true,
    },
    template: {
        one: "Template",
        word: "template",
        many: "Templates",
        icon: "layout",
        intro: "Starting points for new documents and plans.",
        description: "Starting points for documents and plans",
        make: "New template",
    },
    profile: {
        one: "Profile",
        word: "profile",
        many: "Profiles",
        icon: "smile",
        intro: "How the agent addresses you and writes to you.",
        description: "How the agent talks to you",
        make: "New profile",
    },
    share: {
        one: "Share link",
        word: "share link",
        many: "Share links",
        icon: "share",
        intro: "Links that let someone else read one item.",
        description: "Links that let someone read one item",
    },
    plugin: {
        one: "Plugin",
        word: "plugin",
        many: "Plugins",
        icon: "plug",
        intro: "Installed plugins, with their pages and settings.",
        description: "Installed plugins, their pages and settings",
    },
};

export const CARDS = ["waiting", "todo", "question", "suggestion", "plan", "report", "doc", "work", "agent"];
export const kindOf = (type) => KINDS[type] || {one: type, word: type, many: type, icon: "dot", intro: "", description: ""};
export const kindTitle = (type) => KINDS[type]?.one || type;
export const kindWord = (type) => KINDS[type]?.word || type;
export const kindCard = (type) => KINDS[type]?.many || type;
export const kindWaiting = (type) => KINDS[type]?.waiting || kindTitle(type);
