from features.boards.drafting import BUILDING_A_BOARD, DRAFTING, DRAFTING_FROM_A_DOCUMENT, REVISING_THE_DRAFTS
from features.boards.exploration import EXPLORATION
from features.boards.orchestrating import ORCHESTRATING_MOMENTS, ORCHESTRATION

SEQUENCES = (EXPLORATION, DRAFTING, REVISING_THE_DRAFTS, BUILDING_A_BOARD, DRAFTING_FROM_A_DOCUMENT, ORCHESTRATION, *ORCHESTRATING_MOMENTS)
