export const SCHEMES = [
    {key: "journal", name: "Journal", text: "The viewer's own colours", colors: {}},
    {
        key: "github",
        name: "GitHub",
        text: "Light text on dark, with GitHub's blue, green and red",
        colors: {
            "--bg": "#0d1117",
            "--bg-2": "#010409",
            "--raised": "#161b22",
            "--hover": "#1c2128",
            "--sel": "#21262d",
            "--border": "#30363d",
            "--border-2": "#30363d",
            "--border-3": "#484f58",
            "--line": "#21262d",
            "--code-bg": "#0d1117",
            "--text": "#e6edf3",
            "--text-2": "#c9d1d9",
            "--text-3": "#8b949e",
            "--text-4": "#6e7681",
            "--accent": "#1f6feb",
            "--accent-text": "#58a6ff",
            "--accent-dim": "#0d2d6b",
            "--add-bg": "rgba(46, 160, 67, 0.15)",
            "--add-fg": "#3fb950",
            "--del-bg": "rgba(248, 81, 73, 0.15)",
            "--del-fg": "#f85149",
        },
    },
    {
        key: "contrast",
        name: "High contrast",
        text: "Black ground, bright text and strong colours",
        colors: {
            "--bg": "#000000",
            "--bg-2": "#000000",
            "--raised": "#0a0a0a",
            "--hover": "#1a1a1a",
            "--sel": "#262626",
            "--border": "#5a5a5a",
            "--border-2": "#6e6e6e",
            "--border-3": "#8a8a8a",
            "--line": "#3a3a3a",
            "--code-bg": "#000000",
            "--text": "#ffffff",
            "--text-2": "#f0f0f0",
            "--text-3": "#d0d0d0",
            "--text-4": "#a8a8a8",
            "--accent": "#7c83ff",
            "--accent-text": "#c4c8ff",
            "--accent-dim": "#2e3380",
            "--add-bg": "rgba(0, 255, 120, 0.22)",
            "--add-fg": "#5dff9d",
            "--del-bg": "rgba(255, 70, 70, 0.26)",
            "--del-fg": "#ff8a8a",
        },
    },
    {
        key: "soft",
        name: "Soft",
        text: "Muted colours with gentle contrast, easy on the eyes",
        colors: {
            "--bg": "#1a1b1e",
            "--bg-2": "#16171a",
            "--raised": "#1e1f23",
            "--hover": "#232428",
            "--sel": "#28292e",
            "--border": "#2a2c31",
            "--border-2": "#313338",
            "--border-3": "#3b3e44",
            "--line": "#26282c",
            "--code-bg": "#18191c",
            "--text": "#d4d6da",
            "--text-2": "#b0b3b9",
            "--text-3": "#8d9097",
            "--text-4": "#6b6e75",
            "--accent": "#7a7fb8",
            "--accent-text": "#b4b7de",
            "--accent-dim": "#34365a",
            "--add-bg": "rgba(120, 160, 130, 0.1)",
            "--add-fg": "#9dbba6",
            "--del-bg": "rgba(180, 120, 120, 0.1)",
            "--del-fg": "#c49a9a",
        },
    },
];

const named = (key) => SCHEMES.find((s) => s.key === key) || SCHEMES[0];

export const schemeColors = (own, whole) => named(own || whole).colors;

export const schemeChoices = (key) => SCHEMES.map((s) => ({value: s.key, label: s.name, current: s.key === named(key).key}));

export const windowSchemes = (own, whole) => [
    {value: "", label: `Same as the layout (${named(whole).name})`, current: !own},
    ...SCHEMES.map((s) => ({value: s.key, label: s.name, current: s.key === own})),
];
